import type { Lang } from './types';

const DICT = {
  es: {
    nav: { about: 'Nosotros', services: 'Servicios', gallery: 'Viajes', tender: 'Cotizar', testimonials: 'Opiniones' },
    cta: 'Cotizar viaje',
    hero: {
      eyebrow: 'Península de Paraguaná · Desde 2019',
      title1: 'Rutas de',
      titleIt: 'tierra firme',
      title2: 'y mar abierto.',
      sub: 'Viajes y encomiendas confiables entre Paraguaná y el resto del país. Transporte con sello local, chóferes que conocen cada curva del camino.',
      ctaPrimary: 'Cotizar mi viaje',
      ctaSecondary: 'Ver nuestros recorridos',
    },
    marquee: ['Punto Fijo', 'Coro', 'Caracas', 'Valencia', 'Maracaibo', 'Judibana', 'Encomiendas', 'Viajes privados', 'Grupos'],
    about: {
      eyebrow: 'Quiénes somos',
      title1: 'Hechos en',
      titleIt: 'Paraguaná,',
      title2: 'rodando el país.',
      body1: 'Nacimos como un servicio familiar y crecimos hasta convertirnos en la red de viajes más confiable de la península. Cada ruta la hacemos con respeto por el tiempo, la carga y la historia de quien viaja con nosotros.',
      body2: 'Encomiendas puntuales. Viajes seguros. Trato cercano.',
      kpi1: '+6 años', kpi1l: 'de carretera',
      kpi2: '2.400+', kpi2l: 'clientes',
      kpi3: '12', kpi3l: 'rutas activas',
    },
    services: {
      title1: 'Lo que',
      titleIt: 'movemos.',
      lead: 'Dos servicios principales, un solo estándar: puntualidad, cuidado y trato humano.',
      s1Num: 'Servicio 01',
      s1Title: 'Viajes',
      s1Body: 'Traslados cómodos entre Paraguaná, el occidente y el centro del país. Privados o compartidos, con paradas acordadas y espacio para el equipaje real de una familia.',
      s1Tags: ['Privado', 'Compartido', 'Aeropuerto', 'Grupos'],
      s2Num: 'Servicio 02',
      s2Title: 'Encomiendas',
      s2Body: 'Enviamos lo que necesitas llegar a tiempo: documentos, repuestos, mercancía, cajas familiares. Recogida puerta a puerta y entrega con confirmación.',
      s2Tags: ['Puerta a puerta', 'Rastreo', 'Mismo día', 'Carga especial'],
    },
    gallery: {
      eyebrow: 'Galería',
      title1: 'Los viajes',
      titleIt: 'que ya rodamos.',
      lead: 'Fotos enviadas por la familia Viajeros Paraguaná. ¿Fuiste con nosotros? Súbela tú también.',
      all: 'Todos', trips: 'Viajes', pkg: 'Encomiendas', clients: 'Clientes',
      upload: 'Subir tu foto',
      uploadHint: 'JPG o PNG · máx 10MB',
    },
    testimonials: {
      eyebrow: 'Opiniones',
      title1: 'La gente',
      titleIt: 'que nos recomienda.',
      lead: 'Cada viaje es un voto de confianza. Estas son algunas de las voces que nos acompañan.',
    },
    tender: {
      eyebrow: 'Cotización',
      title1: 'Pídenos tu',
      titleIt: 'cotización.',
      lead: 'Cuéntanos a dónde vas o qué necesitas enviar. Te respondemos por WhatsApp en menos de 2 horas en horario laboral.',
      name: 'Nombre completo', namePh: 'María Rodríguez',
      from: 'Desde', fromPh: 'Punto Fijo',
      to: 'Hasta', toPh: 'Caracas',
      type: 'Tipo de servicio',
      typeOpt: ['Selecciona una opción', 'Viaje', 'Encomienda'],
      phone: 'Teléfono', phonePh: '+58 414 000 0000',
      heard: '¿Cómo supiste de nosotros?',
      heardOpt: ['Selecciona una opción', 'Instagram', 'Facebook', 'TikTok', 'WhatsApp', 'Recomendación', 'Google', 'Otro'],
      notes: 'Detalles del viaje o encomienda (opcional)',
      notesPh: 'Fecha tentativa, cantidad de pasajeros, tamaño del paquete...',
      consent: 'Al enviar aceptas que te contactemos por WhatsApp o teléfono para coordinar tu servicio.',
      submit: 'Enviar solicitud',
      info1l: 'Oficina', info1v: 'Av. Jacinto Lara, Punto Fijo',
      info2l: 'WhatsApp', info2v: '+58 414 000 0000',
      info3l: 'Horario', info3v: 'Lun–Sáb · 7am – 7pm',
      successT: '¡Solicitud enviada!',
      successB: 'Gracias por confiar en Viajeros Paraguaná. Te contactaremos muy pronto.',
    },
    footer: {
      tag: 'Viajes y encomiendas desde la península.',
      explore: 'Explora',
      contact: 'Contacto',
      social: 'Redes',
      rights: '© 2026 Viajeros Paraguaná. Todos los derechos reservados.',
      made: 'Hecho con cariño en Paraguaná',
    },
  },
  en: {
    nav: { about: 'About', services: 'Services', gallery: 'Trips', tender: 'Quote', testimonials: 'Reviews' },
    cta: 'Request a quote',
    hero: {
      eyebrow: 'Paraguaná Peninsula · Since 2019',
      title1: 'Routes of',
      titleIt: 'solid ground',
      title2: 'and open sea.',
      sub: 'Reliable travel and parcel service between Paraguaná and the rest of the country. Local-owned transport with drivers who know every curve of the road.',
      ctaPrimary: 'Get a quote',
      ctaSecondary: 'See our routes',
    },
    marquee: ['Punto Fijo', 'Coro', 'Caracas', 'Valencia', 'Maracaibo', 'Judibana', 'Parcels', 'Private trips', 'Groups'],
    about: {
      eyebrow: 'Who we are',
      title1: 'Made in',
      titleIt: 'Paraguaná,',
      title2: 'rolling the country.',
      body1: 'We started as a small family service and grew into the peninsula\'s most reliable travel network. Every route is driven with respect for your time, your cargo and the story of whoever travels with us.',
      body2: 'Punctual parcels. Safe trips. Real conversation.',
      kpi1: '6+ years', kpi1l: 'on the road',
      kpi2: '2,400+', kpi2l: 'clients',
      kpi3: '12', kpi3l: 'active routes',
    },
    services: {
      title1: 'What we',
      titleIt: 'move.',
      lead: 'Two core services, one standard: on time, careful, human.',
      s1Num: 'Service 01',
      s1Title: 'Trips',
      s1Body: 'Comfortable transfers between Paraguaná, the west and the center of the country. Private or shared, with agreed stops and room for real family luggage.',
      s1Tags: ['Private', 'Shared', 'Airport', 'Groups'],
      s2Num: 'Service 02',
      s2Title: 'Parcels',
      s2Body: 'We move what needs to arrive on time: documents, spare parts, goods, family boxes. Door-to-door pickup, confirmed delivery.',
      s2Tags: ['Door to door', 'Tracking', 'Same day', 'Special cargo'],
    },
    gallery: {
      eyebrow: 'Gallery',
      title1: 'The trips',
      titleIt: "we've already run.",
      lead: 'Photos sent in by the Viajeros Paraguaná family. Traveled with us? Drop yours in too.',
      all: 'All', trips: 'Trips', pkg: 'Parcels', clients: 'Clients',
      upload: 'Upload your photo',
      uploadHint: 'JPG or PNG · 10MB max',
    },
    testimonials: {
      eyebrow: 'Reviews',
      title1: 'The people',
      titleIt: 'who vouch for us.',
      lead: "Every trip is a vote of confidence. Here are some of the voices who've come along for the ride.",
    },
    tender: {
      eyebrow: 'Quote',
      title1: 'Ask for your',
      titleIt: 'quote.',
      lead: "Tell us where you're going or what you need to send. We'll reply on WhatsApp within 2 business hours.",
      name: 'Full name', namePh: 'Maria Rodriguez',
      from: 'From', fromPh: 'Punto Fijo',
      to: 'To', toPh: 'Caracas',
      type: 'Service type',
      typeOpt: ['Select an option', 'Trip', 'Parcel'],
      phone: 'Phone', phonePh: '+58 414 000 0000',
      heard: 'How did you hear about us?',
      heardOpt: ['Select an option', 'Instagram', 'Facebook', 'TikTok', 'WhatsApp', 'Referral', 'Google', 'Other'],
      notes: 'Trip or parcel details (optional)',
      notesPh: 'Tentative date, number of passengers, package size...',
      consent: 'By submitting you agree we can contact you on WhatsApp or phone to coordinate your service.',
      submit: 'Send request',
      info1l: 'Office', info1v: 'Av. Jacinto Lara, Punto Fijo',
      info2l: 'WhatsApp', info2v: '+58 414 000 0000',
      info3l: 'Hours', info3v: 'Mon–Sat · 7am – 7pm',
      successT: 'Request sent!',
      successB: "Thanks for trusting Viajeros Paraguaná. We'll be in touch shortly.",
    },
    footer: {
      tag: 'Travel and parcels from the peninsula.',
      explore: 'Explore',
      contact: 'Contact',
      social: 'Social',
      rights: '© 2026 Viajeros Paraguaná. All rights reserved.',
      made: 'Made with care in Paraguaná',
    },
  },
} as const;

export default DICT;
export type Dict = typeof DICT;
export type LangDict = typeof DICT[Lang];
