import { User } from './User';
import { Role } from './Role';
import { ServiceType } from './ServiceType';
import { Service } from './Service';
import { GalleryItem } from './GalleryItem';
import { ContactInfo } from './ContactInfo';
import { SocialLink } from './SocialLink';
import { Review } from './Review';
import { QuoteRequest } from './QuoteRequest';

export const models = {
  User,
  Role,
  // Public content for the landing page — see features/keystone/models/shared.ts
  ServiceType,
  Service,
  GalleryItem,
  ContactInfo,
  SocialLink,
  Review,
  // Landing form submissions: read-only, written only via sudo() from
  // app/api/quote/route.ts. Keep last — features/keystone/view-order is
  // generated by walking this object in order.
  QuoteRequest,
};

export default models;
